export const LiveDataConstant = {
  MAIN_HEADING: 'MAI',
  DASHBOARD: 'Dashboard',
  INTERNET_SPEED: 'internet Speed',
  MARKETING_ANALYSIS: 'Marketing Analysis',
  USER_STATISTICS: 'User Statistics',
  INTERNET_KEY_MATRIX: 'Key Metrics - Internet Speed',
  LATEST: 'Latest',
  AVERAGE: 'Average',
  MIN: 'Min',
  MAX: 'Max',
  DATA_TABLE: 'Data Table with Filters',
  VALUE: 'Value',
  ALL_DATA: 'All Data',
  KEY_MATRIX: 'Key Metrics',
  TOTAL_DATA_POINTS: 'Total Data Points',
  AVERAGE_VALUE: 'Average Value',
  MAXIMUM_VALUE: 'Maximum Value',
  MINIMUM_VALUE: 'Minimum Value',
  FILTER_DATASET: 'Filter by Dataset',
};
